export let ERROR = {
    USER_NOT_FOUND: "USER_NOT_FOUND",
    USER_MENTIONNED_NOT_FOUND: "USER_MENTIONNED_NOT_FOUND",
    USER_UPLOADED_BY_NOT_FOUND: "USER_UPLOADED_BY_NOT_FOUND",
    IMAGE_NOT_FOUND: "IMAGE_NOT_FOUND",
    ACCESS_DENIED: "ACCESS_DENIED",
    OAUTH_LOGIN_FAILED: "OAUTH_LOGIN_FAILED",
};
