name: CD

on:
  push:
    branches:
      - master

jobs:
  deploy-frontend:
    name: deploy-frontend
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
      - uses: borales/actions-yarn@master
      - name: build
        run: |
          cd frontend/
          sudo yarn install
          sudo yarn build:staging
      - name: deploy
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_STAGING }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ca-central-1"
          SOURCE_DIR: "./frontend/build/."
  
  deploy-backend:
    runs-on: [ubuntu-latest]
    name: deploy-backend
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@master
      - uses: borales/actions-yarn@master
      - name: build
        run: |
          cd backend/
          sudo yarn install
          sudo yarn build
          sudo zip -r deployment.zip .
          
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
          
      
      - name: Beanstalk deploy
        uses: einaregilsson/beanstalk-deploy@master
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: "ca-central-1"
          application_name: ${{ secrets.AWS_APPLICATION_NAME }}
          environment_name: ${{ secrets.AWS_APPLICATION_ENVIRONMENT_NAME_STAGING }}
          version_label: "ugram-backend-staging${{ steps.format-time.outputs.replaced }}"
          deployment_package: backend/deployment.zip